### ISSUE TITLE
Uncaught (in promise) TypeError: ASM_CONSTS[I] is not a function

### ISSUE THREAD

**Issue by greensquares** [glowingjade/obsidian-smart-composer#99] opened 2024-11-12 21:26 UTC
I am having an issue similar to #95  but my installer version is up to date and my errors are a bit different. I was able to reproduce this in the sandbox workspace.

`Uncaught (in promise) TypeError: ASM_CONSTS[I] is not a function
    at runEmAsmFunction (plugin:smart-composer:300:4910)
    at _emscripten_asm_const_int (plugin:smart-composer:300:4953)
    at postgres.wasm.main (postgres.wasm-02840556:0x256fe1)
    at callMain (plugin:smart-composer:300:236228)
    at l (plugin:smart-composer:300:236544)
    at run (plugin:smart-composer:300:236681)
    at I (plugin:smart-composer:300:235968)
    at removeRunDependency (plugin:smart-composer:298:76368)
    at l (plugin:smart-composer:298:78408)
    at eval (plugin:smart-composer:300:246386)`

`app.js:1 Failed to open view RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (plugin:smart-composer:298:76498)
    at __abort_js (plugin:smart-composer:299:64513)
    at postgres.wasm.abort (postgres.wasm-02840556:0x6d6d64)
    at postgres.wasm.ExceptionalCondition (postgres.wasm-02840556:0x5f0dcc)
    at postgres.wasm.pg_re_throw (postgres.wasm-02840556:0x5eb5ae)
    at invoke_v (plugin:smart-composer:300:229210)
    at postgres.wasm.PortalRun (postgres.wasm-02840556:0x3eca58)
    at postgres.wasm.exec_simple_query (postgres.wasm-02840556:0x3ff710)
    at postgres.wasm.interactive_file (postgres.wasm-02840556:0x3f8f3f)
    at postgres.wasm.RePostgresSingleUserMain (postgres.wasm-02840556:0x3f8c19)`
    
    Obsidian debug info:
    
    `SYSTEM INFO:
	Obsidian version: v1.7.6
	Installer version: v1.7.6
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 24.1.0
	Login status: not logged in
	Language: en
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Smart Composer v1.0.4`

**Comment by glowingjade** [comment] 2024-11-12 22:34
Thank you for reporting this issue. Since you were able to reproduce it, could you share the steps to reproduce?
Also, it would be very helpful if you could create a minimal reproducible example in a public repository.

**Comment by kevin-on** [comment] 2024-11-13 15:22
Thanks for reporting this. This is a bug in our code and the fix is ready in [PR #100](https://github.com/glowingjade/obsidian-smart-composer/pull/100), pending review and merge. We'll release the update as soon as it's merged.

**Closed** 2024-11-13 19:49 UTC
Labels: bug
