### ISSUE TITLE
Can't rebuild entire vault index when I use both Chat model and Apply model with Custom (OpenAl Compatible)?

### ISSUE THREAD

**Issue by jiabai** [glowingjade/obsidian-smart-composer#182] opened 2024-12-28 16:33 UTC
![smart-composer](https://github.com/user-attachments/assets/012616ec-9507-48b4-8394-625400cec574)
Is this a bug, or is it a feature that hasn't been fully implemented yet?
my config below
![custom model](https://github.com/user-attachments/assets/28cc5b57-89d4-4e9f-b49b-4f7e3a1c2cc4)

And...is it possible to add a feature for printing debug information? This would be particularly helpful when the embedding model does not support customization, as it would allow me to verify whether the embedding model specified by the plugin is usable in China. Currently, I am uncertain if the designated embedding model works properly within China due to potential regional restrictions or compatibility issues.

**Comment by jiabai** [comment] 2024-12-28 17:00
I understand now. The issue is that the embedding model does not support custom models, and the plugin-specified OpenAI embedding model requires an OpenAI API key. This is why the error occurred.

**Comment by glowingjade** [comment] 2024-12-29 00:41
> I understand now. The issue is that the embedding model does not support custom models, and the plugin-specified OpenAI embedding model requires an OpenAI API key. This is why the error occurred.

That's right. We're going to support custom models for embedding model too, stay tuned!

**Comment by kevin-on** [comment] 2024-12-31 02:12
Closing this issue as it is duplicate of #127

**Closed by kevin-on** 2024-12-31 02:12 UTC
