### ISSUE TITLE
use custom llm settings

### ISSUE THREAD

**Issue by kms9** [glowingjade/obsidian-smart-composer#161] opened 2024-12-11 10:35 UTC
like the obsidian plug textgenerator:  "https://github.com/nhaouari/obsidian-textgenerator-plugin"

![image](https://github.com/user-attachments/assets/53435967-3b3e-4403-a9e8-0d94bb54ecef)

**Comment by kevin-on** [comment] 2024-12-11 10:52
To set OpenAI-compatible endpoints, select "Custom (OpenAI Compatible)" for either the chat model or the apply model. At present, we do not support custom embedding models or saving multiple custom model options.
<img width="795" alt="image" src="https://github.com/user-attachments/assets/24607a4d-250f-4e9d-b8cd-b2cf223918f4">

**Comment by kms9** [comment] 2024-12-13 13:42
I've tried this approach, but I still can't use an openai API based on proxy forwarding, such as Raycast

**Comment by Kevin7Qi** [comment] 2024-12-14 05:43
Second this. It would be great to have custom model endpoints implemented at the API level rather than just the model level. For example, I’m currently using third-party providers for the text-small-embedding model, but the current setup doesn’t support this approach. It would be amazing if we could define a custom endpoint for the API and then select the models within the model settings.

**Comment by glowingjade** [comment] 2024-12-14 15:49
@kms9  Could you share what error you encounter? It's supposed to work with any OpenAI-compatible API.

@Kevin7Qi  Could you explain what "custom model endpoints at the API level" means?
For now, we only support custom models for chat/apply. Custom embedding model support is coming soon.

**Comment by Kevin7Qi** [comment] 2024-12-14 16:15
@glowingjade Sorry for any confusion in my earlier comment. What I meant is the ability to customize the endpoints for API providers, allowing us to configure third-party provider endpoints compatible with OpenAI or Anthropic API formats as the default API endpoint. This would enable seamless integration by setting a custom endpoint for these services, without needing to manually specify the model name in the settings.

**Comment by glowingjade** [comment] 2024-12-16 06:24
@Kevin7Qi Thanks for clarifying! We'll work on separating the provider and model settings to make it easier to switch between different models and endpoints. Stay tuned for updates!

**Comment by kevin-on** [comment] 2024-12-31 02:16
Closing this as a duplicate of #149 . Let's continue the discussion there.

**Closed** 2024-12-31 02:16 UTC
