### ISSUE TITLE
[FR] Rendering mathematical formula

### ISSUE THREAD

**Issue by wwjCMP** [glowingjade/obsidian-smart-composer#179] opened 2024-12-26 12:13 UTC
Hope the plugin can render mathematical formulas that appear in the answers.

**Comment by kevin-on** [comment] 2024-12-26 12:31
Hi! Is this feature request similar to what was discussed in #144 ?

**Comment by wwjCMP** [comment] 2024-12-26 14:04
> Hi! Is this feature request similar to what was discussed in #144 ?

yes，it is.

**Comment by kevin-on** [comment] 2024-12-31 02:09
We will close this issue as it is a duplicate of #144. Thank you for the request.

**Closed** 2024-12-31 02:10 UTC
